version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - OPENWEATHERMAP_API_KEY=your_api_key_here  # Замени на свой API-ключ
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=weather_db
      - POSTGRES_USER=weather_user
      - POSTGRES_PASSWORD=weather_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: